### ISSUE TITLE
Error thrown when given an int type where FSharp.Json expects a string

### ISSUE THREAD

**Issue by oauo** [vsapronov/FSharp.Json#19]
If a type is set to an int and the given JSON gives a string an error is thrown rather than just converting the string to an int. This is particuarly useful when you have keys which are numbers but have to be represented as strings.

**Comment by vsapronov** [comment]
Hi Zoe!
Could you please provide an example for this one? I need both F# record
type and JSON sample.
Thank you.

**Comment by oauo** [comment]
```fsharp
let foo = "{\"0\":\"Foo\"}" |> Json.deserialize<Map<int,string>>
```

error
```
System.ArgumentException: 'Object of type 'System.String' cannot be converted to type 'System.Int32'.'
```

**Comment by vsapronov** [comment]
This behavior is intentional. FSharp.Json makes only obvious [type conversions](https://github.com/vsapronov/FSharp.Json#supported-types). For example: (F#) `byte` -> (JSON) `number` is obvious conversion. Other example would be: (F#) `bool` -> (JSON) `bool`.

You want FSharp.Json to make obvious types conversion: (JSON) string -> (F#) int. Such conversion should be configured explicitly. You can try to achieve this with custom [type transforms](https://github.com/vsapronov/FSharp.Json#type-transform).

As a side note: JSON that uses integer as a object property name is not designed well.
The `Map<int,string>` does not have any meaningful default representation in JSON. Most straight-forward guess is not valid JSON:
```JSON
{1: "foo", 2: "bar"} //this is not valid object number can't be object property name
```
I would really consider changing format to something like:
```JSON
[{"key": 1, "value": "foo"}, {"key": 2, "value": "bar"}]
```
